# Generated by Django 5.2.8 on 2025-11-18 19:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('data_fundacao', models.DateField(verbose_name='Data Fundação')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
            },
        ),
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=100)),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_kungfu.escola')),
            ],
            options={
                'verbose_name': 'Membro da Diretoria',
                'verbose_name_plural': 'Diretoria',
            },
        ),
        migrations.CreateModel(
            name='Faixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=50)),
                ('grau', models.CharField(max_length=50)),
                ('tempo_medio_graduacao', models.IntegerField(help_text='Tempo em dias que o aluno deve permanecer nesta faixa.')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_kungfu.escola')),
            ],
            options={
                'verbose_name': 'Faixa/Graduação',
                'verbose_name_plural': 'Faixas/Graduações',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('kati', models.CharField(help_text='Kati, Kata ou Quantidade necessária.', max_length=100)),
                ('faixa_necessaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_kungfu.faixa')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='CalendarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateTimeField()),
                ('vagas', models.IntegerField(default=1)),
                ('faixa_alvo', models.ForeignKey(help_text='Nível/Faixa dos alunos esperados nesta aula', on_delete=django.db.models.deletion.CASCADE, to='gestao_kungfu.faixa')),
            ],
            options={
                'verbose_name': 'Calendário de Aula',
                'verbose_name_plural': 'Calendário de Aulas',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('tipo', models.CharField(help_text='Tipo de Mensalidade/Inscrição', max_length=50)),
                ('situacao_financeira', models.CharField(max_length=50)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_kungfu.escola')),
                ('faixa_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_na_faixa', to='gestao_kungfu.faixa')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_graduacao', models.DateField(default=django.utils.timezone.now)),
                ('aprovado', models.BooleanField(default=False)),
                ('motivo', models.TextField(blank=True, help_text='Feedback ou motivo da reprovação/aprovação', null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_kungfu.aluno')),
                ('faixa_nova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduacoes_concedidas', to='gestao_kungfu.faixa')),
            ],
            options={
                'verbose_name': 'Graduação',
                'verbose_name_plural': 'Histórico de Graduações',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=255)),
                ('tempo_medio_aprendizado', models.CharField(max_length=100)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_kungfu.escola')),
                ('faixa_alvo', models.ForeignKey(blank=True, help_text='Faixa requerida para o programa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_kungfu.faixa')),
            ],
            options={
                'verbose_name': 'Programa de Treinamento',
                'verbose_name_plural': 'Programas de Treinamento',
            },
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestao_kungfu.aluno')),
                ('diretoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_kungfu.diretoria')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_kungfu.escola')),
            ],
            options={
                'verbose_name': 'Instrutor',
                'verbose_name_plural': 'Instrutores',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenca', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_kungfu.aluno')),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_kungfu.calendarioaula')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_kungfu.programa')),
                ('instrutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_kungfu.instrutor')),
            ],
            options={
                'verbose_name': 'Registro de Aula',
                'verbose_name_plural': 'Registros de Aulas',
            },
        ),
    ]
