# Generated by Django 5.2.8 on 2025-11-24 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_kungfu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_desativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Desativação'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_inclusao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='aula',
            name='data_desativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Desativação'),
        ),
        migrations.AddField(
            model_name='aula',
            name='data_inclusao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='calendarioaula',
            name='data_desativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Desativação'),
        ),
        migrations.AddField(
            model_name='calendarioaula',
            name='data_inclusao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='diretoria',
            name='data_desativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Desativação'),
        ),
        migrations.AddField(
            model_name='diretoria',
            name='data_inclusao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_desativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Desativação'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_inclusao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='escola',
            name='data_desativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Desativação'),
        ),
        migrations.AddField(
            model_name='escola',
            name='data_inclusao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='faixa',
            name='data_desativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Desativação'),
        ),
        migrations.AddField(
            model_name='faixa',
            name='data_inclusao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='graduacao',
            name='data_desativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Desativação'),
        ),
        migrations.AddField(
            model_name='graduacao',
            name='data_inclusao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='instrutor',
            name='data_desativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Desativação'),
        ),
        migrations.AddField(
            model_name='instrutor',
            name='data_inclusao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='programa',
            name='data_desativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Desativação'),
        ),
        migrations.AddField(
            model_name='programa',
            name='data_inclusao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
