# Generated by Django 5.2.8 on 2025-11-25 20:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_kungfu', '0002_aluno_data_desativacao_aluno_data_inclusao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aproveitamento', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='Aproveitamento (1-5)')),
                ('comportamento', models.CharField(default='Normal', max_length=50, verbose_name='Comportamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Adicionais')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_detalhes', to='gestao_kungfu.aula')),
                ('instrutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_kungfu.instrutor')),
            ],
            options={
                'verbose_name': 'Ocorrência da Aula',
                'verbose_name_plural': 'Ocorrências das Aulas',
            },
        ),
    ]
