# Generated by Django 5.2.8 on 2025-11-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_kungfu', '0003_ocorrenciaaula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocorrenciaaula',
            old_name='data_registro',
            new_name='data_inclusao',
        ),
        migrations.AddField(
            model_name='ocorrenciaaula',
            name='compareceu',
            field=models.BooleanField(default=False, verbose_name='Compareceu à Aula'),
        ),
        migrations.AddField(
            model_name='ocorrenciaaula',
            name='data_desativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Desativação'),
        ),
    ]
