# Generated by Django 5.2.8 on 2025-11-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_kungfu', '0004_rename_data_registro_ocorrenciaaula_data_inclusao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faixa',
            name='elegivel_instrutor',
            field=models.BooleanField(default=False, help_text='Define se alunos nesta faixa podem ser promovidos a instrutor.', verbose_name='Elegível para Instrutor'),
        ),
    ]
