"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+k*9vt+t983l2b_j=o80+h+(22z1jd)*^&=r0!chzv_-#4ic(9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 1. Apps de Terceiros Necessários
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken', # <--- ESTA LINHA É OBRIGATÓRIA!

    # 2. Seu Aplicativo Personalizado (Crie-o a seguir!)
    'gestao_kungfu', # <--- Nome do App que contém os Models (Escola, Aluno, etc.)
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # DEVE SER O PRIMEIRO OU O SEGUNDO DA LISTA
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kungfudata',  # Nome do DB que criamos
        'USER': 'root',            # Usuário padrão do MySQL
        'PASSWORD': '728460@Mysql', # <-- ***COLOQUE SUA SENHA DO MYSQL AQUI***
        'HOST': 'localhost',
        'PORT': '3306',
        # Configurações adicionais para garantir compatibilidade com MySQL 8.x
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo' # Ajuste para seu fuso horário

USE_I18N = True

USE_TZ = True # Mantenha True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py

# ----------------------------------------
# CONFIGURAÇÕES DE CORS
# ----------------------------------------

# Permite que cookies e cabeçalhos de autenticação sejam trocados entre origens (domínios/portas)
CORS_ALLOW_CREDENTIALS = True

# Permite requisições de sites específicos (apenas localhost:3000 para desenvolvimento)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3001",   # <--- NOVO ORIGEM!
    "http://127.0.0.1:3001",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Permite que o navegador envie o cabeçalho Authorization (necessário para o Token)
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization', # Crucial para enviar 'Authorization: Token XYZ'
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Permite todos os métodos (GET, POST, PUT, DELETE, OPTIONS)
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'POST',
    'PUT',
]